FROM php:8.1-rc-cli-alpine3.16

WORKDIR /var/www/html

# Install RabbitMQ extension dependencies
RUN apk update && apk add --no-cache rabbitmq-c rabbitmq-c-dev

# Install Composer
ENV COMPOSER_ALLOW_SUPERUSER=1
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --ignore-platform-reqs

# Copy the consumer script to the container
COPY ./src/scripts/consumer.php .

# Install project dependencies
RUN composer require php-amqplib/php-amqplib

CMD ["php", "consumer.php"]